
<?php
//
// ph07b : liste des polygones avec un tableau
//
$polygones = array(
  1 => "hénagone ou monogone",
  2 => "digone",
  3 => "triangle ou trigone",
  4 => "quadrilatère ou tétragone",
  5 => "pentagone",
  6 => "hexagone",
  7 => "heptagone",
  8 => "octogone",
  9 => "ennéagone ou nonagone",
  10 => "décagone",
  11 => "hendécagone",
  12 => "dodécagone",
  13 => "triskaidécagone ou tridécagone",
  14 => "tétrakaidécagone ou tétradécagone, quadridécagone",
  15 => "pentakaidécagone ou pentadécagone, quidécagone",
  16 => "hexakaidécagone ou hexadécagone",
  17 => "heptakaidécagone ou heptadécagone",
  18 => "octakaidécagone ou octadécagone",
  19 => "ennéakaidécagone ou ennéadécagone",
  20 => "icosagone",
  21 => "icosikaihenagone ou henicosagone",
  22 => "icosikaidigone ou doicosagone",
  23 => "icosikaitrigone ou triaicosagone",
  24 => "icosikaitétragone ou tétraicosagone",
  25 => "icosikaipentagone ou pentaicosagone",
  26 => "icosikaihexagone ou hexaicosagone",
  27 => "icosikaiheptagone ou heptaicosagone",
  28 => "icosikaioctagone ou octaicosagone",
  29 => "icosikaiennéagone ou ennéaicosagone",
  30 => "triacontagone",
  31 => "triacontakaihenagone ou hentriacontagone",
  32 => "triacontakaidigone ou dotriacontagone",
  33 => "triacontakaitrigone ou tritriacontagone",
  34 => "triacontakaitétragone ou tétratriacontagone",
  35 => "triacontakaipentagone ou pentatriacontagone",
  36 => "triacontakaihexagone ou hexatriacontagone",
  37 => "triacontakaiheptagone ou heptatriacontagone",
  38 => "triacontakaioctogone ou octatriacontagone",
  39 => "triacontakaiennégone ou ennéatriacontagone",
  40 => "tétracontagone",
  50 => "pentacontagone",
  60 => "hexacontagone",
  70 => "heptacontagone",
  80 => "octacontagone",
  90 => "ennéacontagone",
  100 => "hectogone ou hécatontagone",
  200 => "dihectogone",
  300 => "trihectogone",
  400 => "tétrahectogone",
  500 => "pentahectogone",
  600 => "hexahectogone",
  700 => "heptahectogone",
  800 => "octahectogone",
  900 => "ennéahectogone",
  1000 => "chiliogone ou chiliagone ou chiligone",
  10000 => "myriagone ou myriogone"
);